# Generated by Django 6.0.1 on 2026-02-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
