# Generated by Django 6.0.2 on 2026-02-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_registration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
    ]
